'use strict';

const MAX_CHARS_PER_LINE = 90;
const FONT_SIZE_PER_CONSOLE_WIDTH = 0.02;
const MILLISECONDS_PER_CHAR = 10;
const MILLISECONDS_PER_WORD = MILLISECONDS_PER_CHAR * 2;
const MILLISECONDS_PER_LINE = MILLISECONDS_PER_CHAR * 5;
const CLASS_ACTIVATOR = '§';