'use strict';

const MAX_CHARS_PER_LINE = 90;
const FONT_SIZE_PER_CONSOLE_WIDTH = 0.02;
const MILLISECONDS_PER_CHAR = 20;
const MILLISECONDS_PER_WORD = MILLISECONDS_PER_CHAR * 4;
const MILLISECONDS_PER_LINE = MILLISECONDS_PER_CHAR * 20;
const CLASS_ACTIVATOR = '§';